osx_image: xcode9
language: objective-c

script:
  - set -o pipefail && xcodebuild -project Family.xcodeproj -scheme "Family-macOS" -sdk macosx clean build
  - set -o pipefail && xcodebuild -project Family.xcodeproj -scheme "Family-macOS" -sdk macosx -enableCodeCoverage YES test
  - set -o pipefail && xcodebuild -project Family.xcodeproj -scheme "Family-iOS" -sdk iphonesimulator -destination name="iPhone 6" clean build
  - set -o pipefail && xcodebuild -project Family.xcodeproj -scheme "Family-iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0' -enableCodeCoverage YES test
  - set -o pipefail && xcodebuild -project Family.xcodeproj -scheme "Family-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=11.0' clean build
  - set -o pipefail && xcodebuild -project Family.xcodeproj -scheme "Family-tvOS" -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=11.0' -enableCodeCoverage YES test

notifications:
  email: false
